version: '3'
services:
  zabbix-proxy-sqlite3:
    image: lgti/zabbix-proxy-sqlite3:centos-5.2.6
    ports:
      - '10051:10051'
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - zabbix-proxy:/var/lib/zabbix
      - /home/zabbix/proxy.key:/var/lib/zabbix/enc/proxy.key
      - /etc/odbc.ini:/etc/odbc.ini
      #- /etc/odbcinst.ini:/etc/odbcinst.ini
    environment:
     - 'ZBX_SERVER_HOST=zabbix.smarapd.com.br'
     - 'ZBX_SERVER_PORT=10051'
     - 'ZBX_HOSTNAME=proxy-pmituiutaba'
     - 'ZBX_PROXYLOCALBUFFER=24'
     - 'ZBX_PROXYOFFLINEBUFFER=24'
     - 'ZBX_PROXYHEARTBEATFREQUENCY=60'
     - 'ZBX_CONFIGFREQUENCY=600'
     - 'ZBX_ENABLEREMOTECOMMANDS=1'
     - 'ZBX_DATASENDERFREQUENCY=30'
     - 'ZBX_STARTPOLLERS=15'
     - 'ZBX_IPMIPOLLERS=1'
     - 'ZBX_STARTPOLLERSUNREACHABLE=10'
     - 'ZBX_STARTPREPROCESSORS=10'
     - 'ZBX_STARTHTTPPOLLERS=15'
     - 'ZBX_STARTTRAPPERS=20'
     - 'ZBX_STARTPINGERS=15'
     - 'ZBX_STARTDISCOVERERS=5'
     - 'ZBX_STARTVMWARECOLLECTORS=15'
     - 'ZBX_VMWAREFREQUENCY=60'
     - 'ZBX_VMWAREPERFFREQUENCY=60'
     - 'ZBX_VMWARECACHESIZE=256M'
     - 'ZBX_VMWARETIMEOUT=300'
     - 'ZBX_CACHESIZE=512M'
     - 'ZBX_STARTDBSYNCERS=8'
     - 'ZBX_HISTORYCACHESIZE=32M'
     - 'ZBX_HISTORYINDEXCACHESIZE=32M'
     - 'ZBX_TIMEOUT=30'
     - 'ZBX_TLSPSKFILE=proxy.key'
     - 'ZBX_TLSPSKIDENTITY=proxy_psk'
     - 'ZBX_TLSCONNECT=psk'
     - 'ZBX_TLSACCEPT=psk'
     - 'ZBX_JAVAGATEWAY=zabbix-java-gateway'
     - 'ZBX_JAVAGATEWAYPORT=10052'
     - 'ZBX_STARTJAVAPOLLERS=5'
     - 'ZBX_JAVAGATEWAY_ENABLE=true'
  zabbix-java-gateway:
    image: zabbix/zabbix-java-gateway:5.2.6-ubuntu
    ports:
      - '10052:10052'
    environment:
      - 'ZBX_START_POLLERS=5'
      - 'ZBX_TIMEOUT=30'
volumes:
  zabbix-proxy:
  
